name: lawyer_erp
description: An example project for flutter-desktop-embedding.

version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  provider: ^3.2.0
  table_calendar: ^2.2.1
  rxdart: ^0.22.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/wall.jpg
    - welcome_side.jpg
    - assets/logo.png
    - assets/admin.jpeg
    - assets/placeholder.png
    - assets/lawyer-512.png
    - assets/image002.png

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/tajwal/Tajawal-ExtraLight.ttf
          weight: 100
        - asset: fonts/tajwal/Tajawal-Light.ttf
          weight: 300
        - asset: fonts/tajwal/Tajawal-Regular.ttf
          weight: 400
        - asset: fonts/tajwal/Tajawal-Medium.ttf
          weight: 500
        - asset: fonts/tajwal/Tajawal-Bold.ttf
          weight: 700
        - asset: fonts/tajwal/Tajawal-Black.ttf
          weight: 900
